// Главный файл экспорта всех stores
export { useAuthStore } from './auth'
export { useCartStore } from './cart'
export { useProductsStore } from './products'
export { useGeoStore } from './geo'
export { useCategoriesStore } from './categories'
export { useOrdersStore } from './orders'
export { useFavoritesStore } from './favorites'
export { useElasticSearchStore } from './elasticSearch'
export { usePersonalStore } from './personal'
export { useReviewsStore } from './reviews'
export { useSMSStore } from './sms'
export { useStaticStore } from './static'
export { useStoriesStore } from './stories'
export { useShowcaseStore } from './showcase'
export { useErrorStore } from './error'
export { useSEOStore } from './seo'
export { usePaymentStore } from './payment'
export { useCardsStore } from './cards'
export { useLoyaltyStore } from './loyalty'
export { useProvidersStore } from './providers'
export { useRedirectStore } from './redirect'
export { useHomepageTagsStore } from './homepageTags'
export { useActionsStore } from './actions'

// Главный store для инициализации
export { useAppStore } from './app'
